parameters:
  track[]:
  - 1
  jyo[]:
  - '01'
  - '02'
  - '03'
  - '04'
  - '05'
  - '06'
  - '07'
  - '08'
  - '09'
  - '10'
  start_year: 2021
  start_mon: 1
  end_year: 2021
  end_mon: 12
  grade[]:
  - 1
  list: 100
result:
  output: result/test.csv