parameters:
  track[]:
  - 1
  - 2
  - 3
  start_year: 2021
  start_mon: 1
  end_year: 2021
  end_mon: 1
  jyo[]:
  - '01'
  - '02'
  - '03'
  - '04'
  - '05'
  - '06'
  - '07'
  - '08'
  - '09'
  - '10'
  baba[]:
  - 1
  - 2
  - 3
  - 4
  jyoken[]:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  barei[]:
  - 11
  - 12
  - 13
  - 14
  grade[]:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  kyori_min: 0
  kyori_max: 10000
  list: 100
result:
  output: result/test.csv